name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make all
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: libmemstack.so
        path: libmemstack.so
    - name: Install memstack
      run: sudo make install
    - name: Run tests
      run: cd tests && make all
